//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileSplitter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileSplitter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual file progress.
        /// </summary>
        internal static string ACTUAL_FILE_PROGRESS {
            get {
                return ResourceManager.GetString("ACTUAL_FILE_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files progress.
        /// </summary>
        internal static string ALL_FILES_PROGRESS {
            get {
                return ResourceManager.GetString("ALL_FILES_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        internal static string CMB_LINES {
            get {
                return ResourceManager.GetString("CMB_LINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} File systems does not allow more than {1} {2} for each file..
        /// </summary>
        internal static string ERROR_FILESYSTEM_NOTALLOW_SIZE {
            get {
                return ResourceManager.GetString("ERROR_FILESYSTEM_NOTALLOW_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimun part size must be {0} bytes.
        /// </summary>
        internal static string ERROR_MINIMUN_PART_SIZE {
            get {
                return ResourceManager.GetString("ERROR_MINIMUN_PART_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Space available to split.
        /// </summary>
        internal static string ERROR_NO_SPACE_TO_SPLIT {
            get {
                return ResourceManager.GetString("ERROR_NO_SPACE_TO_SPLIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening {0}.
        /// </summary>
        internal static string ERROR_OPENING_FILE {
            get {
                return ResourceManager.GetString("ERROR_OPENING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total size of all the output file parts is not equal to the original data file size !.
        /// </summary>
        internal static string ERROR_TOTALSIZE_NOTEQUALS {
            get {
                return ResourceManager.GetString("ERROR_TOTALSIZE_NOTEQUALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FILE {
            get {
                return ResourceManager.GetString("FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files|*.*.
        /// </summary>
        internal static string FILE_EXTENSIONS {
            get {
                return ResourceManager.GetString("FILE_EXTENSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of rows.
        /// </summary>
        internal static string NUMBER_OF_LINES {
            get {
                return ResourceManager.GetString("NUMBER_OF_LINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 parts of.
        /// </summary>
        internal static string SPLINT_INFO_PARTS_DEF {
            get {
                return ResourceManager.GetString("SPLINT_INFO_PARTS_DEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First select a file to split. Next select the part size and  push on &quot;Start&quot; to start splitting the file in smaller parts.
        /// </summary>
        internal static string SPLIT_INFO {
            get {
                return ResourceManager.GetString("SPLIT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} parts of.
        /// </summary>
        internal static string SPLIT_INFO_PARTS {
            get {
                return ResourceManager.GetString("SPLIT_INFO_PARTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Size.
        /// </summary>
        internal static string SPLITSIZE {
            get {
                return ResourceManager.GetString("SPLITSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitting file {0}.
        /// </summary>
        internal static string SPLITTING_FILE {
            get {
                return ResourceManager.GetString("SPLITTING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string START {
            get {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Splitter.
        /// </summary>
        internal static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
    }
}
