name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore FileSplitter/FileSplitter.csproj

      - name: Build
        run: dotnet build FileSplitter/FileSplitter.csproj --configuration Release --no-restore -v detailed -ds

      - name: Install Test dependencies
        run: dotnet restore FileSplitter.Tests/FileSplitter.Tests.csproj        

      - name: Test
        run: dotnet test FileSplitter.Tests/FileSplitter.Tests.csproj --no-restore -v detailed -ds