name: dotnet package

on: [push]

jobs:
  build:

    runs-on: windows-latest
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: false
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore FileSplitter.csproj

      - name: Build
        run: dotnet build FileSplitter.csproj --configuration Release --no-restore -v detailed -ds

      - name: Install Test dependencies
        run: dotnet restore FileSplitter.Tests.csproj

      - name: Test
        run: dotnet test FileSplitter.Tests.csproj --no-restore -v detailed -ds
